### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by aleshkanet** [Taiterio/ce#26] opened 2016-03-03 15:40 UTC
Drag placing(right-click and move) was cancelling in workbench.

**Comment by RoboMWM** [comment] 2016-03-12 11:24
Most likely a duplicate of #23 - what version of Custom Enchantments are you using?

**Comment by Taiterio** [comment] 2016-03-27 01:35
Closing as it seems like an outdated problem, reopen if necessary.

**Closed by Taiterio** 2016-03-27 01:35 UTC
